# pandas Basics Practice

## Goal
Practice creating DataFrames and selecting data using pandas.

## Topics Covered

This notebook documents practice from all six Kaggle Pandas sections.

1. **Creating, Reading, and Writing**: DataFrames, Series, and CSV files.
2. **Indexing, Selecting, and Assigning**: `loc`, `iloc`, filters, and new columns.
3. **Summary Functions and Maps**: descriptive statistics, `map()`, and `apply()`.
4. **Grouping and Sorting**: `groupby()`, aggregations, and sorting results.
5. **Data Types and Missing Values**: inspecting, converting, finding, and filling data.
6. **Renaming and Combining**: renaming columns, concatenating, and merging DataFrames.

In [2]:
import pandas as pd

In [3]:
students = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "marks": [82, 91, 76, 65, 58],
    "hours_studied": [4, 5, 3, 2, 1]
})

students

  name  marks  hours_studied
0    A     82              4
1    B     91              5
2    C     76              3
3    D     65              2
4    E     58              1

In [4]:
students.loc[:, "name"]

0    A
1    B
2    C
3    D
4    E
Name: name, dtype: object

In [5]:
students.loc[:, "marks"]

0    82
1    91
2    76
3    65
4    58
Name: marks, dtype: int64

In [6]:
students.loc[:, ["name", "marks"]]

  name  marks
0    A     82
1    B     91
2    C     76
3    D     65
4    E     58

In [7]:
students.iloc[0]

name              A
marks            82
hours_studied     4
Name: 0, dtype: object

In [8]:
students.iloc[:3]

  name  marks  hours_studied
0    A     82              4
1    B     91              5
2    C     76              3

In [9]:
students.iloc[0, 1]

np.int64(82)

In [10]:
students[students.marks >= 70]

  name  marks  hours_studied
0    A     82              4
1    B     91              5
2    C     76              3

In [11]:
students[students.hours_studied > 3]

  name  marks  hours_studied
0    A     82              4
1    B     91              5

In [12]:
students[(students.marks >= 70) & (students.hours_studied > 3)]

  name  marks  hours_studied
0    A     82              4
1    B     91              5

In [13]:
study_hours = pd.Series([3, 3, 2, 4, 3, 5, 1], name="daily_study_hours")

study_hours

0    3
1    3
2    2
3    4
4    3
5    5
6    1
Name: daily_study_hours, dtype: int64

In [14]:
study_hours[0]

np.int64(3)

In [15]:
study_hours.iloc[-1]

np.int64(1)

In [16]:
study_hours.iloc[:3]

0    3
1    3
2    2
Name: daily_study_hours, dtype: int64

In [17]:
study_hours.sum()

np.int64(21)

In [18]:
study_hours.mean()

np.float64(3.0)

In [19]:
skills = pd.DataFrame({"skill" : ["AI", "DSA", "ML", "Cyber", "Web3"], "difficulty" : [5, 3, 4, 3, 3], "priority" : ["High", "Low", "High", "Low", "Low"]})
skills

   skill  difficulty priority
0     AI           5     High
1    DSA           3      Low
2     ML           4     High
3  Cyber           3      Low
4   Web3           3      Low

In [20]:
skills.skill

0       AI
1      DSA
2       ML
3    Cyber
4     Web3
Name: skill, dtype: object

In [21]:
skills.loc[:, ["skill", "priority"]]

   skill priority
0     AI     High
1    DSA      Low
2     ML     High
3  Cyber      Low
4   Web3      Low

In [22]:
skills[skills.difficulty >= 4]

  skill  difficulty priority
0    AI           5     High
2    ML           4     High

In [23]:
skills[skills.priority == "High"]

  skill  difficulty priority
0    AI           5     High
2    ML           4     High

## 3. Summary Functions and Maps

In [24]:
students

  name  marks  hours_studied
0    A     82              4
1    B     91              5
2    C     76              3
3    D     65              2
4    E     58              1

In [25]:
students.describe()

           marks  hours_studied
count   5.000000       5.000000
mean   74.400000       3.000000
std    13.164346       1.581139
min    58.000000       1.000000
25%    65.000000       2.000000
50%    76.000000       3.000000
75%    82.000000       4.000000
max    91.000000       5.000000

In [26]:
students.marks.mean()

np.float64(74.4)

In [27]:
students.marks.max()

91

In [28]:
students.marks.min()

58

In [29]:
students.hours_studied.unique()

array([4, 5, 3, 2, 1])

In [30]:
students.hours_studied.value_counts()

hours_studied
4    1
5    1
3    1
2    1
1    1
Name: count, dtype: int64

In [31]:
new_series = students.marks + 5
new_series

0    87
1    96
2    81
3    70
4    63
Name: marks, dtype: int64

In [32]:
new_series.map(lambda mark: "Pass" if mark >= 70 else "Needs Improvement")

0                 Pass
1                 Pass
2                 Pass
3                 Pass
4    Needs Improvement
Name: marks, dtype: object

In [33]:
students["adjusted_marks"] = students.marks.map(lambda m: m + 5)
students

  name  marks  hours_studied  adjusted_marks
0    A     82              4              87
1    B     91              5              96
2    C     76              3              81
3    D     65              2              70
4    E     58              1              63

In [34]:
students["status"] = students.marks.map(lambda mark: "Pass" if mark >= 70 else "Needs Improvement")
students

  name  marks  hours_studied  adjusted_marks             status
0    A     82              4              87               Pass
1    B     91              5              96               Pass
2    C     76              3              81               Pass
3    D     65              2              70  Needs Improvement
4    E     58              1              63  Needs Improvement

In [35]:
def effort_label(row):
    if row.hours_studied >= 4:
        return "High Effort"
    else:
        return "Low Effort"

students["Effort"] = students.apply(effort_label, axis = "columns")
students

  name  marks  hours_studied  adjusted_marks             status       Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

## 4. Grouping and Sorting

In [36]:
students

  name  marks  hours_studied  adjusted_marks             status       Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

In [37]:
students.groupby(["status"]).size()

status
Needs Improvement    2
Pass                 3
dtype: int64

In [38]:
students.groupby(["status"]).marks.mean()

status
Needs Improvement    61.5
Pass                 83.0
Name: marks, dtype: float64

In [39]:
students.groupby(["status"]).hours_studied.mean()

status
Needs Improvement    1.5
Pass                 4.0
Name: hours_studied, dtype: float64

In [40]:
students.groupby(["status"]).marks.agg(["max", "min"])

                   max  min
status
Needs Improvement   65   58
Pass                91   76

In [41]:
students.groupby(["Effort"]).size()

Effort
High Effort    2
Low Effort     3
dtype: int64

In [42]:
students.groupby(["Effort"]).marks.mean()

Effort
High Effort    86.500000
Low Effort     66.333333
Name: marks, dtype: float64

In [43]:
students.sort_values(by = ["marks"])

  name  marks  hours_studied  adjusted_marks             status       Effort
4    E     58              1              63  Needs Improvement   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
2    C     76              3              81               Pass   Low Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort

In [44]:
students.sort_values(by = ["marks"], ascending= False)

  name  marks  hours_studied  adjusted_marks             status       Effort
1    B     91              5              96               Pass  High Effort
0    A     82              4              87               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

In [45]:
students.sort_values(by = ["hours_studied"], ascending= False)

  name  marks  hours_studied  adjusted_marks             status       Effort
1    B     91              5              96               Pass  High Effort
0    A     82              4              87               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

In [46]:
students.sort_values(by = ["status", "marks"])

  name  marks  hours_studied  adjusted_marks             status       Effort
4    E     58              1              63  Needs Improvement   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
2    C     76              3              81               Pass   Low Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort

In [47]:
students.sort_values(by = ["Effort", "marks"], ascending= [True, False])

  name  marks  hours_studied  adjusted_marks             status       Effort
1    B     91              5              96               Pass  High Effort
0    A     82              4              87               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

In [48]:
sales = pd.DataFrame({
    "product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Tablet"],
    "region": ["North", "North", "South", "South", "South", "North"],
    "units": [5, 10, 3, 7, 8, 2],
    "revenue": [5000, 7000, 3000, 2800, 5600, 800]
})

sales

  product region  units  revenue
0  Laptop  North      5     5000
1   Phone  North     10     7000
2  Laptop  South      3     3000
3  Tablet  South      7     2800
4   Phone  South      8     5600
5  Tablet  North      2      800

In [49]:
sales.groupby(["product"]).revenue.sum()

product
Laptop     8000
Phone     12600
Tablet     3600
Name: revenue, dtype: int64

In [50]:
sales.groupby(["region"]).units.sum()

region
North    17
South    18
Name: units, dtype: int64

In [51]:
sales.groupby(["product"]).revenue.mean()

product
Laptop    4000.0
Phone     6300.0
Tablet    1800.0
Name: revenue, dtype: float64

In [52]:
sales.sort_values(by = ["revenue"], ascending= False)

  product region  units  revenue
1   Phone  North     10     7000
4   Phone  South      8     5600
0  Laptop  North      5     5000
2  Laptop  South      3     3000
3  Tablet  South      7     2800
5  Tablet  North      2      800

In [53]:
sales.groupby(["product", "region"]).revenue.sum()

product  region
Laptop   North     5000
         South     3000
Phone    North     7000
         South     5600
Tablet   North      800
         South     2800
Name: revenue, dtype: int64

## 5. Data Types and Missing Values

In [54]:
students

  name  marks  hours_studied  adjusted_marks             status       Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort

In [57]:
students.dtypes

name              object
marks              int64
hours_studied      int64
adjusted_marks     int64
status            object
Effort            object
dtype: object

In [58]:
students.marks.dtype

dtype('int64')

In [59]:
students.marks.astype("float64")

0    82.0
1    91.0
2    76.0
3    65.0
4    58.0
Name: marks, dtype: float64

In [61]:
students.status.astype(str)

0                 Pass
1                 Pass
2                 Pass
3    Needs Improvement
4    Needs Improvement
Name: status, dtype: object

In [62]:
students_missing = pd.DataFrame({
    "name": ["A", "B", "C", None, "E"],
    "marks": [82, None, 76, 65, None],
    "hours_studied": [4, 5, None, 2, 1]
})

students_missing

   name  marks  hours_studied
0     A   82.0            4.0
1     B    NaN            5.0
2     C   76.0            NaN
3  None   65.0            2.0
4     E    NaN            1.0

In [63]:
students_missing.isnull()

    name  marks  hours_studied
0  False  False          False
1  False   True          False
2  False  False           True
3   True  False          False
4  False   True          False

In [64]:
students_missing.isnull().sum(axis = "index")

name             1
marks            2
hours_studied    1
dtype: int64

In [65]:
students_missing[students_missing.marks.isnull()]

  name  marks  hours_studied
1    B    NaN            5.0
4    E    NaN            1.0

In [71]:
students_missing.marks = students_missing.marks.fillna(0)

In [72]:
students_missing.name = students_missing.name.fillna("Unknown")
students_missing

      name  marks  hours_studied
0        A   82.0            4.0
1        B    0.0            5.0
2        C   76.0            3.0
3  Unknown   65.0            2.0
4        E    0.0            1.0

In [73]:
students_missing.hours_studied = students_missing.hours_studied.fillna(students_missing.hours_studied.mean())
students_missing

      name  marks  hours_studied
0        A   82.0            4.0
1        B    0.0            5.0
2        C   76.0            3.0
3  Unknown   65.0            2.0
4        E    0.0            1.0

## 6. Renaming and Combining

In [75]:

students_renamed = students.rename(columns={
    "name": "student_name",
    "marks": "original_marks",
    "hours_studied": "study_hours"
})

students_renamed

,student_name,original_marks,study_hours,adjusted_marks,status,Effort
0,A,82,4,87,Pass,High Effort
1,B,91,5,96,Pass,High Effort
2,C,76,3,81,Pass,Low Effort
3,D,65,2,70,Needs Improvement,Low Effort
4,E,58,1,63,Needs Improvement,Low Effort

In [76]:

new_students = pd.DataFrame({
    "name": ["F", "G"],
    "marks": [88, 72],
    "hours_studied": [4, 3],
    "adjusted_marks": [93, 77],
    "status": ["Pass", "Pass"],
    "Effort": ["High Effort", "Low Effort"]
})

all_students = pd.concat([students, new_students], ignore_index=True)
all_students

  name  marks  hours_studied  adjusted_marks             status       Effort
0    A     82              4              87               Pass  High Effort
1    B     91              5              96               Pass  High Effort
2    C     76              3              81               Pass   Low Effort
3    D     65              2              70  Needs Improvement   Low Effort
4    E     58              1              63  Needs Improvement   Low Effort
5    F     88              4              93               Pass  High Effort
6    G     72              3              77               Pass   Low Effort

In [77]:
student_goals = pd.DataFrame({
    "name": ["A", "B", "C", "D", "E"],
    "goal": ["AI", "Data Analysis", "Machine Learning", "Web Development", "Cybersecurity"]
})

students_with_goals = students.merge(student_goals, on="name", how="left")
students_with_goals

,name,marks,hours_studied,adjusted_marks,status,Effort,goal
0,A,82,4,87,Pass,High Effort,AI
1,B,91,5,96,Pass,High Effort,Data Analysis
2,C,76,3,81,Pass,Low Effort,Machine Learning
3,D,65,2,70,Needs Improvement,Low Effort,Web Development
4,E,58,1,63,Needs Improvement,Low Effort,Cybersecurity